### PR TITLE
Some fixes in Sound + uos.

### PR DESCRIPTION
**Pull request by fredvs**

### CODE REVIEW

**Comment by rchastain** [comment]
Thank you Fred.

**Comment by fredvs** [comment]
Hello Roland.

I have to go.

I will try to find a Windows 10 machine tomorrow and test, sorry but uos cannot stay like this.

Fre;D

**Comment by rchastain** [comment]
Hello Fred! I am looking for the memory leak. I believe it isn't relative to uos, but to pictures.
Regards.
Roland

**Comment by fredvs** [comment]
Hello Roland.
I did test Eschecs-audio on some Windows 10 machines.
I did not note some delay nor quality problems (if you do not use DEBUG mode)

I updated uos code to disable DEBUG mode for Windows.
It seems that it is too hard for the heart of Windows.

For last commits of Portaudio library, there is no change in the Windows code vs the version given by uos.

Fre;D

**Pull request merged**
