### PR TITLE
Some checks to make Eschecs more errors friendly (message if errors).

### PR DESCRIPTION
**Pull request by fredvs**
Hello Roland.

I was on Windows 10 and your last commit.

If compiling with `-ghl` and **with** `-WG`, message when close:

> Segmentation fault
> #7  5788 unknown 0x0041d483 in CLASSES$_$TLIST_$__$$_GETCOUNT$$LONGINT ()
> 

But If compiling with `-ghl` and **without** `-WG`,  message when close:

> Heap dump by heaptrc unit
> 7591 memory blocks allocated : 5269445/5286104
> 7591 memory blocks freed     : 5269445/5286104
> 0 unfreed memory blocks : 0
> True heap size : 163840 (96 used in System startup)
> True free heap : 163744
> 

For me there is no more memory leak but a problem with heap-trace in GUI mode.
So, IMHO, it is ok for release.

In the pull-request, some checks to make Eschecs more errors friendly (message if errors).

A very little detail, I commented the message if  `Colored Square` state was changed (cause it is dynamic).
But maybe it was wanted so, sorry for this.

OK, je vous passe la main.

Fre;D

### CODE REVIEW

**Comment by rchastain** [comment]
Thank you Fred!

**Comment by rchastain** [comment]
If it is OK for you, it is OK for me.

I still get from time to time a message which looks to be relative to this line:
`fpgImages.AddMaskedBMP('vfd.eschecs', @vfd_eschecs, sizeof(vfd_eschecs), 0, 0);`
That's why I was wondering if there wasn't something to free when the program closes.

No, coloring option is not changed instantly, but when the app restarts (like style and language). I have tried to make it change instantly, but it was a Chinese puzzle and I didn't want to spend too time on that. If you please, I will come back later to that issue.

**Comment by rchastain** [comment]
I "created" some new images sets, for the 480 chessboard: Alpha, Montreal.
If you want to try them, you have to set the "font" field in the INI file with value "alpha" or "montreal".

**Comment by fredvs** [comment]
> I still get from time to time a message which looks to be relative to this line:

When does it append ?
A loading of Eschecs, when a ShowMessageform appear, or randomly?
(It must be fixed).

**Comment by fredvs** [comment]
> you have to set the "font" field in the INI file with value "alpha" or "montreal".

Huh, something more friendly than edit a file (Ho, I am bad)?

**Comment by rchastain** [comment]
Hello Fred! The bug appears when Eschecs closes. But, as I said, it doesn't always appear. I will try to understand in which condition it appears.

Of course, it would be good to have menu items for chess pieces selection. But for now, it's just an experimental feature.

**Comment by rchastain** [comment]
I forgot to say that ideU is very nice. 👍

**Comment by fredvs** [comment]
> Hello Fred! The bug appears when Eschecs closes. 

Could you try with the last pull-request ?
With your last release, I have to set eco.pas in mode Delphi.
Once again, mystery of informatic, why now the conversion of integer -> object is invalid....
Anyway, setting eco.pas in Delphi mode solve it. (but still mystery),

Sorry, I did not yet test your new images, I will do it tonight.

> I forgot to say that ideU is very nice

Thanks Roland.  If you use ideU, please before to do the pull-request, save your eschecs.prj and use this one after the pull request.

In the future I will use only make option 5,6,7,8 for Linux from your eschecs.prj.

Fre;D

**Comment by fredvs** [comment]
> I forgot to say that ideU is very nice.

Thanks but when I used yesterday ideU on Windows 10, I have noted that if you select a project or a file in the list-box of the "Commander", that file is not loaded.

I will do some more extensive test of ideU on Windows 10.
(Of course if you note something, it would be highly appreciated to share it).

Fre;D

**Comment by rchastain** [comment]
I believe I can explain the mystery. On your computer, the code wasn't compiled because you didn't have -dOPT_ECO. On my computer, it compiled successfully because I have "-Sh" in my options.

**Comment by rchastain** [comment]
I am not sure to understand what you say about eschecs.prj.

**Comment by fredvs** [comment]
> The bug appears when Eschecs closes.

Ooops, in earlier pull-request I forgot to add last commit.
Maybe with last pull-request it will be better?

**Superbes** your new images!

About .prj, in _Project Option_ (or icon _tools_ in commander-form) , tab _Make_,:
you have make-option M,B,1,2,3,4,5,6,7,8,9,0.

For example one for debug, a other with some options, etc,
You may configure each make-option like you want.

To switch make-option, in commander-form, choose one in the listbox.
I propose to let you M,B,1,2,3,4 for Windows and I will use 5,6,7,8

Fre;D

**Comment by rchastain** [comment]
Re-hello Fred!
Thank for your commit and your message.
No more error message. The bug seems to be solved. Congratulations!
OK for eschecs.prj.
Regards.
Roland

**Comment by fredvs** [comment]
Yep. ;)

I did a last pull-request, in case of.

Fre;D

**Pull request merged**
