### PR TITLE
Added LICENSE.md and some carriage-return in other md files.

### PR DESCRIPTION
**Pull request by fredvs**
Hello Roland.

You forgot to add a important file: LICENSE.md (and the same in release for license.txt).

Please check the LICENSE.md fille and update it if needed.

Fre;D

### CODE REVIEW

**Comment by fredvs** [comment]
Re-hello Roland.

Huh, in last commit, in readme.md, (because of total truth), I did adjust this:

> concerning **Linux** compatibility

with

> concerning **Unix** compatibility

This because Eschecs is not only Linux compatible but FreeBSD too.

;)

Fre;D

**Comment by rchastain** [comment]
Thank you Fred.

**Comment by rchastain** [comment]
Hello Fred! Not really convinced by your modifications in _readme.md_. The first link (on the words "uci protocol") isn't displayed correctly. On the other hand, there is no reason to put a carriage return after each sentence. It looks ugly.
To avoid too long lines in .txt file, we can use a conversion tool like Pandoc, instead of simply changing the file extension.
Regards.
Roland

**Comment by rchastain** [comment]
Anyway, I had the intention to rectify some little things in readme files, so it isn't a problem. ;)

**Comment by fredvs** [comment]
> Not really convinced by your modifications in readme.md

It is not me, chef, it is Github that, after `git commit --all` advised:
 "All carriages where replaced with LT (or something like that)"

I did try to re-add it but yes, it was not perfect.
Sorry for that.

> To avoid too long lines in .txt file

That would be the top.

**Comment by fredvs** [comment]
I have difficult access to Internet.

So I will wait for your next pre-release until tomorrow.

PS: Yes, it is always like that, before release all details appear and the release "tarde".

Fre;D

**Comment by rchastain** [comment]
Thank you for your messages, Fred.

I tried the conversion with Pandoc. I will use it when I will have retouched the .md files.

I am always impressed by your usage of french words. :)

Regards.

Roland

**Comment by fredvs** [comment]
> I am always impressed by your usage of french words

My Monther tongue is French.
I do not use a lot this language anymore.
But I still dream en Français.

Fre;D

**Comment by rchastain** [comment]
Je comprends mieux à présent. :)

I must go. Have a good night Fred!

**Pull request merged**
