### PR TITLE
Sound uses uos_MemoryStream().

### PR DESCRIPTION
**Pull request by fredvs**
Is it better?

### CODE REVIEW

**Comment by rchastain** [comment]
Thank you for the commit.
It looks like something needs to be fixed. In debug mode I can see too many operations.

```
EndProc---
EndProc All
This is the end...
EndProc---
EndProc All
This is the end...
EndProc---
EndProc All
This is the end...
EndProc---
EndProc All
This is the end...
EndProc---
EndProc All
This is the end...
EndProc---
EndProc All
This is the end...
```

**Comment by rchastain** [comment]
In release mode, I get a EInOut Error. Probably a WriteLn somewhere. :)

I wait that you repair the code before making my opinion about the final result.

**Comment by fredvs** [comment]
OK, I have sent you a message about this.

About the debug mode, you with -dDEBUG you set uos in debug too.

OK, I do a new-pull request.

**Comment by rchastain** [comment]
There are parasitic noise. It reminds me when I used MMSystem. I hope it will disappear if you fix the code.

**Comment by fredvs** [comment]
OK, I will find a Windows 10 machine to test.

The pull request was done.

**Comment by fredvs** [comment]
Did you try both version: Windows 32 bit and Windows 64 bit ?

**Pull request merged**
