### PR TITLE
Some fixes (?) for icon-image in resource. Changing in eco.pas --> mo…

### PR DESCRIPTION
**Pull request by fredvs**
…de Delphi (otherwise invalid conversion).

### CODE REVIEW

**Comment by rchastain** [comment]
> 
> 
> …de Delphi (otherwise invalid conversion).

I believe that "{$mode delphi}{$H+}" is not necessary: "{$H+}" is enough. (See my command line options.)

**Comment by fredvs** [comment]
> Unfortunately I still get the same message:

Hello Roland.
I hope that last pull-request fix it.
If no, tomorrow I will test on a Windows 10 machine.

Maybe it is related with some `fpgapplication.processmessage`  (or a `sleep(10)`) at closing the application needed for Windows 10.

Fre;D

**Comment by fredvs** [comment]
Re-hello Roland.

Maybe you may try adding at end of eschecs.pas this:

```
Close(vLog); 
    Close(vUCILog);
    fpgApplication.terminate;  //////////////////// Add this 
  end else 
  begin
    ShowMessagefrm('The config folder is corrupted.', 'Please check your configuration or reinstall Eschecs.', 'Error...', 'Close');
    fpgApplication.terminate;
  end;  
end.
```

**Comment by rchastain** [comment]
Re-hello Fred! OK, I add it.

**Pull request merged**
