### PR TITLE
First shot of Eschecs sound with uos.

### PR DESCRIPTION
**Pull request by fredvs**
Hello Roland.

Here first shot of Eschecs + uos.

The source of uos are in /libraries/uos/.
I added only the files needed by Eschecs.

Dont forget to add that directory in the search path.
And use the `-dOPT_SOUND` compiler parameter.

Please copy the /audio directory that is in root Eschecs directory
into the main directory of the executable.
It contains sounds + libraries.

There is only one sound (at the moment).
In `TMainForm.OnMoveDone()` I did comment all the "`if`" to keep only one: `PlaySound(sndMove);`

Of course it must be updated but so you may try the audio.

On this commit, uos uses `uos_AddFromFile()` but if you prefer, 
it can use also `uos_AddFromMemoryStream()`.

Fre;D

### CODE REVIEW

**Comment by rchastain** [comment]
Hello Fred! Thank you for your work. Compilation OK.

My first feeling, after a quick test, is that the sound comes too late after the event. (It was to solve the same problem that I had replaced MMSystem with Bass.)

I see that the file is opened and read when the Play procedure is called. For music it would be ok, but for a sound effect it isn't. The sound should be heard immediately after the event.

So yes, I would like to experiment the uos_AddFromMemStream solution.

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.
OK, I will change it.
(here on Linux we do not have that problem!).

Fre;D

**Comment by rchastain** [comment]
OK Fred, thank you.

**Comment by fredvs** [comment]
For info, what Windows version are you using?

Because here on Linux there is no delay using the wine emulator (or few milli seconds).
Using a memorystream will reduce the delay but it was nearly 0.

**Comment by rchastain** [comment]
It's Windows 10.

The first solution I tried was MMSystem. Sometimes you were waiting the sound for two of three seconds. :)

**Comment by rchastain** [comment]
I believe that the Bass unit, under Windows, uses something like this:

initialization
  TimeBeginPeriod(1);
finalization
  TimeEndPeriod(1);

It speeds up the system. We could use the same code in Eschecs (just an idea).

**Comment by rchastain** [comment]
Anyway, there is no emergency to solve the sound question. The compilation option works perfectly, so we could make a release without sound.

**Comment by fredvs** [comment]
Hello.
There is a pull-request.

**Comment by fredvs** [comment]
```
 believe that the Bass unit, under Windows, uses something like this:

initialization
TimeBeginPeriod(1);
finalization
TimeEndPeriod(1);
```

Are TimeBeginPeriod(1); TimeEndPeriod(1); from Windows system (or Bass specific) ?

**Pull request merged**
