### PR TITLE
Some last things.

### PR DESCRIPTION
**Pull request by fredvs**

### CODE REVIEW

**Comment by rchastain** [comment]
Hello Fred! Thank you for your work. The status bar is nice.
For me, I created a credits file. See last commit.
Tell me if I can do something else. Please include Fruit and Moustique source code. For Moustique I would prefer a directory.

```
moustique\moustique.exe
moustique\source\moustique.pas
```

For Fruit, we can include the zip file, since we haven't modified the code.

```
fruit\fruit.exe
fruit\fruit.zip
```
But why not also a "source" folder, one rule for all engines?

Regards.
Roland

**Comment by rchastain** [comment]
For the "let me win" setting, I promise it for the next version. ;)

But, you know, Moustique isn't very strong. I believe that if you want,  you can beat it. :)

Don't forget Moustique logo (please put it in the same directory than **eschecs.exe**). Thanks!

**Comment by fredvs** [comment]
Hello Roland.

> For me, I created a credits file

Good idea.  How you did for Github with only one README.md is perfect.
But for the release, IMHO a short readme.txt and a long credit.txt !


> But why not also a "source" folder, one rule for all engines?

It is what I thought.

About `book_small.bin`

Sorry but I do not catch his function.
It seems to be a binary. Is the source disposable and free?

Fre;D

**Comment by fredvs** [comment]
When you are ready, feel free to create the first "Alpha-pre-release" on github-release or where you want.
I will use this as layout for Linux/FreeBSD release.

Fre;D

**Comment by rchastain** [comment]
Re-hello Fred!

book_small.bin is an opening book in the [Polyglot format](http://hgm.nubati.net/book_format.html).

When you ask Fruit a move for a position which is in the book, Fruit returns the move from the book without "thinking".

**Comment by rchastain** [comment]
OK I will try to create a release for Win32.

**Comment by rchastain** [comment]
[Done](https://github.com/rchastain/eschecs/releases/tag/v4.0.0-alpha).

I uploaded engines before I understood that it wasn't necessary. Sorry for that. I will delete it.

Do we announce the release on talkchess.com forum (and elsewhere)?

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

OK, downloaded.
I will check/do it tonight.

Fre;D

**Comment by fredvs** [comment]
> Do we announce the release on talkchess.com forum (and elsewhere)?

IMHO, when the "real" releases (not alpha) are ready, how more announces how better.

Fre;D

**Comment by fredvs** [comment]
Hello Roland.

After first check, please use a Eschecs directory for the zip file.
Zip the all Eschecs directory, not only the binary and sub directories.

For example for Windows 32, the directory will be eschecs_win32 ---> compress that directory (and all what is inside).

Fre;D

**Comment by fredvs** [comment]
Other thing.

Why do you use the *.md extension for text files, why not *.txt ?
.md is a extension used by Github (Standard Markdown).

Ha, for zipped-source, you did not use a common /source folder? 

Fre;D

**Comment by fredvs** [comment]
> I uploaded engines before I understood that it wasn't necessary.

Not sure to understand.
IMHO, it is much better to include in the release the engines with their binaries.
The same for external audio libraries.

I find extremely boring the releases that oblige people to find/install elements to make the release work.

For me a good program must be **OUT-OF-THE-BOX**.

Fre;D

**Comment by fredvs** [comment]
Hello Roland.

Here a other alpha-pre-release.

https://github.com/fredvs/eschecs/releases

Some notes:

- Renamed *.md --> *.txt

- Renamed moustique.exe into moustique32.exe and updated eschecs.eng. (the same must be done for Windows 64 bit)

- Renamed fruit_21.exe into fruit_21_32.exe and updated eschecs.eng. (the same must be done for Windows 64 bit)

- Transfered engine-source-code in /engines/source/source_theengine.zip

About source of moustique.

There is something that I do not catch.
Is moustique licensed LGPL?
If yes, why add the source in the release?
To follow the logic, then fpc, fpGUI, BGrabitmap, uos and all oher LGPL source-code used by Eschecs should be added.

You did clearly mentioned in readme.txt and credits.txt that you used that code, with reference where to find it.

Fre;D

**Comment by fredvs** [comment]
Last thing.

I would prefer different names for eschecs 32 bit vs eschecs 64 bit.
But if you rename eschecs.exe into eschecs32.exe it does not work any more because there is conflict in the LoadEnginesData(), it looks for eschecs.eng in place of eschecs32.eng.
The same for .ini files.

Fre;D

**Comment by rchastain** [comment]
Hello Fred!

OK, I agree all your suggestions.

Of course all binaries will be included. I was speaking of the files that I uploaded to Github, not on the release page, but with the source code.

Wouldn't be easier that you make the release? There is no interest for the project that I remake what you have already made. Please tell me what you think about that.

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

OK, with what you explained about eschecs.debug.

But would it not possible to still use the methods used by for vUCILog and incorporate it in the eschecs.log, so only one file ?

**Comment by rchastain** [comment]
> 
> Hello Roland.
> 
> OK, with what you explained about eschecs.debug.
> 
> But would it not possible to still use the methods used by for vUCILog and incorporate it in the eschecs.log, so only one file ?

Hello Fred! OK for that.

**Comment by rchastain** [comment]
OK for the eschecs_win32 directory, but there are private files inside that I don't intend to include. If you speak of the source code of Eschecs and libraries, I don't see the interest to include it in the binary release. I see an interest to include engines source code.

**Comment by fredvs** [comment]
There is a pull-request.

It add reference to your Github site.

Maybe you may remove the sources-files from the release now, not be obliged to be more catholique que le pape.

Fre;D

**Comment by rchastain** [comment]
> 
> Why do you use the *.md extension for text files, why not *.txt ?
> .md is a extension used by Github (Standard Markdown).
> 

I use .md extension because I use the markdown format. I can remake the files, using plain text, but why?

For the previous versions, I used to convert the .md files to html and include the html in the binary release. I have seen many people who don't know what to do with a .txt file. :)

**Comment by fredvs** [comment]
> I can remake the files, using plain text, but why?

Because it is more universal, everybody can read txt files.
IMHO, how simpler, how better.

But of course for docu, web pages, github presentation pages, .md or .html are welcome.

**Comment by fredvs** [comment]
> Wouldn't be easier that you make the release?

Maybe, but you are the chief and also you will test/compile Eschecs on a real Windows 10 system.
Here all is done via emulator Linux-wine.

**Comment by rchastain** [comment]
> 
> Maybe you may remove the sources-files from the release now, not be obliged to be more catholique que le pape.
> 

Thank you for your french words Fred. :)
The expression that French people use is "plus royaliste que le roi".

On the question of source code, we don't understand each other. Please see my previous message.

**Comment by fredvs** [comment]
> Please see my previous message.

Sorry, but what message?

**Comment by fredvs** [comment]
> but there are private files inside that I don't intend to include. If you speak of the source code of Eschecs and libraries, I don't see the interest to include it in the binary release. I see an interest to include engines source code.

Sorry but I do not understand.

**Comment by fredvs** [comment]
Hello Roland.

About the .md files, is like you want, it was just my opinion.

Fre;D

**Comment by rchastain** [comment]
> Sorry but I do not understand.

It's very simple. I would like to include the engines source code in the release, but not the application source code.
If you believe that it isn't a good idea, please let's do as you suggest to do. ;)

**Comment by rchastain** [comment]
> About the .md files, is like you want, it was just my opinion.

Re-hello Fred!
I have no problem with .txt file, but will we keep also the .md? If yes, each time I will make a modification in the .txt file, I will have to make it also in the .md file.

**Comment by fredvs** [comment]
> If you believe that it isn't a good idea, please let's do as you suggest to do

No it is not a bad idea, I already said you that I am fan of the totally truth and respect but, IMHO, adding the source code of the engine is to be "plus republicain que Macron".

**Comment by rchastain** [comment]
OK Fred, I don't want to be "plus maçonnique que le Grand Orient". :)

**Comment by fredvs** [comment]
> If yes, each time I will make a modification in the .txt file, I will have to make it also in the .md file.

Sorry to not understand.
What dont you like if md is translated into txt ?
There is nothing to change from the .md file, with a classical editor, all appear perfectly, the ** and other symbols uded by md-formatter are not annoying.

**Comment by fredvs** [comment]
> If yes, each time I will make a modification in the .txt file, I will have to make it also in the .md file.

If you change the .md file in github main page, for the release, simply copy it and rename it into .txt

**Comment by fredvs** [comment]
Re-hello Roland.

About the md's files, do like you want, it is detail, sorry to annoy you with this.

**Comment by fredvs** [comment]
Last hello.

I have to go, read you tomorrow.

Fre;D

**Comment by rchastain** [comment]
> the ** and other symbols uded by md-formatter are not annoying.

OK Fred, maybe you are right.

**Comment by rchastain** [comment]
> I have to go, read you tomorrow.

Good night Fred! See you!

**Comment by rchastain** [comment]
Hello Fred! I downloaded alpha2 release. For me, it's perfect.

**Comment by rchastain** [comment]
I uploaded an alpha3 package. I think it's exactly identical to alpha2, excepted that I changed the default style to "Simple". I also replaced the logo file. The new file is the original file.

**Comment by rchastain** [comment]
I have not made all the modifications that you suggested, but I think that some of them can wait until the next version.

If you want, I can make the Win64 package, and let you make the other.

Regards.

Roland

**Comment by rchastain** [comment]
I forgot to put all files in a eschecs_win32 directory. Tomorrow!

**Comment by rchastain** [comment]
Hello Fred !

Uploaded an alpha4 package. The difference with alpha3 is the eschecs_win32 directory.

I am ready to make the package for Win64, if you want.

**Comment by fredvs** [comment]
Hello Roland.

OK, I will check your alpha 4 release.

Write you later this afternoon.

Fre;D

**Comment by fredvs** [comment]
Re-hello Roland.

In https://github.com/rchastain/eschecs/releases the release is 2 days old.

Is it this one that i have to try?

**Comment by fredvs** [comment]
Oooops, OK, I see it, you added last zip-files.

Sorry for the noise.

**Comment by rchastain** [comment]
> In https://github.com/rchastain/eschecs/releases the release is 2 days old.
> 
> Is it this one that i have to try?

Hello Fred! Yes, the release is two days old but I attached a new ZIP file this morning.

**Comment by fredvs** [comment]
Hello Roland.

OK, the last pre-release seems ok.

But you forgot to add a important file: license.txt.

I did a pull-request because that file is missing too in github.

Please check if LICENSE.md is ok, then copy i in release as license.txt.

Fre;D

**Comment by rchastain** [comment]
Thank you Fred. I uploaded an alpha5 package. The only difference with alpha4 is the _license.txt_ file.

So what do we do now?

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

Sorry I did no see this message.

Is alpha5 the really last one (you seems to say in other posts that you want do some modifs)?
IMHO, there are no more problems in Eschecs/Moustique code so I will already compiles Eschecs + Moustique for Linux/Freebsd using your last Github commits..

When you are ready with last fixes in text files, please re-sent the last alpha6 pre-release, so I have the same layout than yours.

Sorry I have to quit, read you tomorrow.

Fre;D

**Comment by rchastain** [comment]
Hello Fred! I have just uploaded alpha6. The difference concerns .txt files, which are now converted by Pandoc instead of being simply renamed. I included .html (also by Pandoc) for you to see it. Tell me if you think we should keep it or not.

**Comment by fredvs** [comment]
Hello Roland.

Yep, internet works (for a short time)!
OK, I will check your last alpha.

By the way, I was able to fix the fpGUI-Rpi bug and compile with success Fruit, Moustique and Eschecs for ARM cpu.

So Rpi is part of the game too.

Fre;D

**Comment by fredvs** [comment]
Hello Roland.

Hum, about the html files, it begins to be lot of same files, readme.txt, readmt.html, lisezmoi.txt, lisezmoi.html....

Like I (already) said  how simpler, how better.

But of course, do like you want.

Fre;D

**Comment by fredvs** [comment]
Hello Roland.

If you want to add infos-files, IMHO, better to create a /doc folder and paste all you want in it.

Fre;D

**Comment by fredvs** [comment]
Re-hello Roland.
I profit that I still connected.
Please check your license text.
It is a copy of fpGUI license and there are some reference to fpGUI.
You should replace all "fpGUI" by "Eschecs".

Fre;D

**Comment by rchastain** [comment]
Hello Fred!

Congratulations for Rpi compilation. 👍 

Fixed license text. See alpha7 package.

Made a package for Win64.

Good night!

Roland

**Comment by rchastain** [comment]
Hello Fred!
I tried to compile Fruit with LLVM but it's too complicated. I give up!
Regards.
Roland

**Comment by fredvs** [comment]
Hello Roland.

IMHO, your last alpha7-release is perfect.

We arrived!
I will do the releases for Linux32, Linux64, FreeBSD64 and Rpi32.

They will be added in https://github.com/fredvs/eschecs/releases.
Then you may download the release and add it in your https://github.com/rchastain/eschecs/releases.

> I tried to compile Fruit with LLVM but it's too complicated.

OK, I will try. (but not for Eschecs now).

Fre;D

**Comment by rchastain** [comment]
Hello Fred!

Congratulations! I have just created the new release.

Tonight I will announce the release on different forums. I will copy here the links to the discussions, so that you can follow them.

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

Did you read my last post ?

The previous eschecs-4.0.0.bsd64.zip was corrupted.
Could you replace with the new one.
More details how to do in my previous post:
https://github.com/rchastain/eschecs/pull/27#issuecomment-443440165

Fre;D

**Comment by rchastain** [comment]
Hello Fred!
Thank you. It's done.
Regards.
Roland

**Comment by fredvs** [comment]
Hello Roland.
Perfect.
Fre;D

**Comment by rchastain** [comment]
Hello Fred!

Here are the discussions where Eschecs 4.0.0 is announced.

https://www.lazarusforum.de/viewtopic.php?f=11&t=9542
https://www.pascalgamedevelopment.com/showthread.php?32456-Eschecs-Pascal-chess-program
http://talkchess.com/forum3/viewtopic.php?f=7&t=68726
https://www.developpez.net/forums/d1248075/autres-langages/pascal/codes-sources-telecharger/eschecs-jeu-d-echecs-mode-graphique/

Regards.

Roland

**Comment by rchastain** [comment]
Hello Fred!

We have finished. Thank you very much for your contribution to the project.

See you!

Roland

**Comment by fredvs** [comment]
Hello Roland.
It was a pleasure to work with you.

About the release, for us it is clear but maybe some people will need explanations in the release-note-panel.

Something like:

> "To install Eschecs just download the zip file for your system:
> 
> For Windows 32 bit: eschecs-4.0.0-win32.zip
> For Windows 64 bit: eschecs-4.0.0-win64.zip
> For Linux 32 bit: eschecs-4.0.0-lin32.zip
> For Linux 64 bit: eschecs-4.0.0-lin64.zip
> For FreeBSD 64 bit: eschecs-4.0.0-bsd64.zip
> For ARM Rpi 32 bit: eschecs-4.0.0-rpi32.zip
>
> Unzip it and 2xclick on eschecs executable:

**Comment by rchastain** [comment]
Hello Fred!
The pleasure was for me.
OK, I will do that.
Regards.
Roland

**Pull request merged**
