### PR TITLE
Fixed default engine for Unix.

### PR DESCRIPTION
**Pull request by fredvs**
Hello Roland.

I think that now the conversion to Unix compatibility is ok.
There is one thing I have doubts.

It is about the directory name that you choose for moustique engine:
/engines/moustique/**0.1**/moustique

I am not sure that /0.1/  will be without problems because the use of the dot ( le point ).
IMHO it would be safer to not use dot for name of directory.

Maybe you could use /01/ (without dot) as name.

Fre;D

### CODE REVIEW

**Comment by rchastain** [comment]
Hello Fred! Ok for "01" (and the same for the other engines).

Did you make a test with Fruit? In previous releases I included Moustique and Fruit. And for each engine I included the source code.

I have no idea how we will proceed to make a release. So I will wait for your instructions. :)

**Comment by fredvs** [comment]
Hello Roland.

I did test Fruit for Windows but did not try Fruit in Linux...

> I have no idea how we will proceed to make a release. So I will wait for your instructions. :)

Huh already ?

Fre;D

**Comment by rchastain** [comment]
Hello Fred.

 

Fruit doesn't really need to be tested. There's no reason why it wouldn't work. But I had the idea to include in future releases two engines, Fruit and Moustique. That is what I wanted to say. :)

 

By the way, I believe that the default engine is no more used in the current version of Eschecs. Now the user has to choose an engine. No engine is automatically loaded. But anyway it's a good thing that you fixed the path.

 

Yes, you are right, we have time to make a release.

 

If I want to make one, I still can use the "harddisk" branch. :)

 

On the Github branch I try to do no modification, first because I don't feel comfortable with the Git system, second because I want let you work.

 

I just changed one set of images (I learned today a method to make them more beautiful) and deleted another set of images. In the current implementation, the user cannot change images: the option is set in the source code.

 

Have a good night!

 

Regards.

 

Roland


Envoyé: mardi 13 novembre 2018 à 20:46
De: "Fred van Stappen" <notifications@github.com>
À: rchastain/eschecs <eschecs@noreply.github.com>
Cc: "Roland Chastain" <roland.chastain@gmx.fr>, "State change" <state_change@noreply.github.com>
Objet: Re: [rchastain/eschecs] Fixed default engine for Unix. (#4)


Hello Roland.

I did test Fruit for Windows but did not try Fruit in Linux...


I have no idea how we will proceed to make a release. So I will wait for your instructions. :)


Huh already ?

Fre;D

**Comment by fredvs** [comment]
Hello Roland.

OK I did find a Linux version of Fruit that I will try tonight.

Before to release next version, IMHO this should be fixed:

- Load default engine at loading of eschecs (so people may directly play).

- Enable marble on/off (to make Graeme happy!).

- Enable green-frame-moving under piece after play on/off (the thing you try to explain).

- Give the chose of mark/fritz/condal images.

Now I will wait your modifs before to add other things (for example I will prefer a custom panel vs the default of fpGUI for ShowMessage that include the fpGUI-icon).

For the release you may use the "release" feature of GitHUB: click on "releases" on your main Eschecs-Github site, then "Add new release"".
It is very simple, just upload the eschecs zip file of the release.

Fre;D

**Comment by fredvs** [comment]
Hello Roland.

Voila, I did try the Linux version of Fruit.
Sadly it did not work.
Here log + debug files of Moustique and Fruit, after loading Eschecs, select a engine and quit.
Maybe you have a idea where is the problem, it seems that uci did not work for Fruit.
(fruit on command line is ok)

For Moustique ----> OK 

eschecs.log:
```
14-11-18 15:55:59 Eschecs 3.1.5 2018/11/14 15:53:25 FPC 3.0.4
14-11-18 15:56:04 Connexion établie.
14-11-18 15:56:04 Protocole accepté. Moteur "Moustique 0.1". Auteur "Juergen Schlottke, Valentin Albillo, Roland Chastain".

```
eschecs.debug:
```
14-11-18 15:56:04 < uci
14-11-18 15:56:04 > id name Moustique 0.1
14-11-18 15:56:04 > id author Juergen Schlottke, Valentin Albillo, Roland Chastain
14-11-18 15:56:04 > uciok
14-11-18 15:56:08 < quit

```
For Fruit ----> Not OK

eschecs.log:
```
14-11-18 16:01:24 Eschecs 3.1.5 2018/11/14 15:53:25 FPC 3.0.4
14-11-18 16:01:33 Connexion établie.

```
eschecs.debug:
```
14-11-18 16:01:33 < uci
14-11-18 16:01:33 > Fruit 2.1 UCI by Fabien Letouzey
14-11-18 16:01:36 < quit

```
________________________________________________________

Here result for Fruit on Windows (OK):

eschecs.log:
```
11/14/2018 16:12:35 Eschecs 3.1.5 2018/11/13 20:34:59 FPC 3.1.1
11/14/2018 16:12:44 Connexion établie.
11/14/2018 16:12:44 Protocole accepté. Moteur "Fruit 2.1". Auteur "Fabien Letouzey".
```

eschecs.debug:
```
11/14/2018 16:12:44 < uci
11/14/2018 16:12:44 > Fruit 2.1 UCI by Fabien Letouzey
11/14/2018 16:12:44 > id name Fruit 2.1
11/14/2018 16:12:44 > id author Fabien Letouzey
11/14/2018 16:17:16 > uciok
11/14/2018 16:17:18 < quit

```

Fre;D

**Comment by rchastain** [comment]
Hello Fred! Thank you very much for your work on the project.

OK for the modifications to do before the next release. I will need time to make it correctly and not introduce too many bugs. :)

Why it doesn't work with Fruit under Linux, unfortunately I have no idea. Currently I have only a Windows machine, so I can't make any test.

Oh yes, I have an idea. Probably it's because of line endings. Maybe there is a simple modification to do in _expressions.pas_, to support Linux line endings. Let me a moment and I come back with a proposition of modification.

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

It should be great to make Fruit work for Linux.
The binary for Linux that they give is 32 bit.
This is a few obsolete because we use in majority Linux 64 bit.
But ok, after few modifs in the Makefile, Fruit compiles and is working in Linux 64 bit.

When I try it on Eschecs,  the log shows that Fruit is working-answering but it does not work because of init ok UCI.

But sure you will find the solution!

OK, I let you in peace.

Fre;D

**Comment by fredvs** [comment]
> expressions.pas

Huh, I do not see that file ;(

Fre;D

**Comment by rchastain** [comment]
Sorry, this isn't _expressions.pas_, but _uci.pas_, in source/uci/.

I think the problem is here, in the IsMsgUciOk() function.

**Comment by fredvs** [comment]
Hello.

Changing:
`with TRegExpr.Create('id name ([^\r\n]+).+id author ([^\r\n]+).+uciok') do`
with this: 
` with TRegExpr.Create('id name ([^/r/n]+).+id author ([^/r/n]+).+uciok') do`

Did not help (it would be strange because it works for Moustique without to change it).

OK, I will try others things.

Fre;D

**Comment by rchastain** [comment]
No, it cannot be that. "\r" means #13 and "\n" means #10, in regular expressions syntax. It isn't directory separator.
But maybe I did send you on a wrong path. Maybe it's rather a problem with the pipes. I say that because Fruit output looks truncated in _eschecs.debug_.
I can't say you more for the moment. I had a work to finish, for my real job. :)
What I could do is to improve the logging/debugging system, so the bug will be easier to find. But for now I have no time.
Thank you again. See you soon!
Regards.
Roland

**Comment by fredvs** [comment]
OK, same for me.

Bon courage.

Fre;D

**Comment by fredvs** [comment]
Hello.

In connect.pas, changing

 `s := aStr + #13#10; `
with this 
 `s := aStr + #10;`

makes Fruit works on Linux.

Tested for Moustique and it works too.
The same for Windows.

;)

```
procedure WriteProcessInput(const aStr: string);
var
  s: string;
begin
  if vProcess.Running then
  begin
    s := aStr + #10;
    vProcess.Input.Write(s[1], Length(s));
  end;
end;
```

OK, fixed and now I **really** let you in peace.

Fre;D

**Comment by rchastain** [comment]
Fred, you are a champion. 👍 
Thank you very much!
Have a good night.
For me, I will think to the modifications that you suggested.
Regards.
Roland

**Comment by rchastain** [comment]
I did build eschecs with your modification in _connect.pas_, and made a test with several engines. It works with all the engines. 👍 

Another thing. It isn't really important, but your _eschecs.prj_ doesn't work here. As we have enough problems with the application itself, wouldn't it be a good idea to keep private these kind of files (_eschecs.prj_, _build.lib.cmd_, _build.cmd_)? Please let me know what you think about that.

**Comment by rchastain** [comment]
For your suggestions about the things to do before the next release, I will try to find an acceptable solution.
Why do I say that?
I have three kind of pictures.

1. Fritz. It comes with its own board (pixel stripes), and is available only in one size (40x40).
2. Pictures made from True Type fonts (Condal, Mark...). They come with the marble chessboard, or with a simple two-color chessboard. Available in different sizes.
3. Daniela Di Lena chess artwork. There is two styles (wood, metal). Each comes with its own board.

Do you see the problem?

That's why I had in mind to define global styles (see _style.pas_) and let to the user only the choice of one global style.
And I had also in mind to load the style from the ini file. The user could edit the ini file and change the value of that parameter. This is the kind of things that a person interested in computer chess can do. I can define styles with marbles and styles without marble. :)
The available styles would be listed in the documentation, with screenshots.
Have a good night.
Regards.
Roland

**Comment by fredvs** [comment]
> but your eschecs.prj doesn't work here. 

Ha ? What did you use MSEide or ideU?
In Project-option, tab "Make" + "Diretories" did you check .../src/corelib/gdi in place of /src/corelib/X11 ?
The prj was set for Linux as main system, you should adapt it for Windows.

I use ideU because it can do cross-compiling.

Anyway, I agree with you, if you give release with binary included (the engines), people dont need source.   Also, like you write, not give builder (eschecs.prj, build.lib.cmd, build.cmd) is less problems for you and only the "purist" will try to compile Eschces.

About my suggestions, of course, you are the boss.

Fre;D

**Pull request merged**
